---
- name: Build openscap report
  hosts: "{{ NODES }}"

  tasks:
    - ansible.builtin.include_role:
        name: vk_shadowman_run_scap
      vars:
        file_path: "/opt/ansible/reports/gps/cis/v3"
        report_svr_path: "gps/cis/v3"
        # file_path: "/opt/ansible/reports/gps/cis/v3/openscap"
        # report_svr_path: "gps/cis/v3/openscap"
