---
- name: RHEL8 CIS Remediation
  hosts: "{{ CIS_SERVERS }}"
  become: true
  vars:
      is_container: false
  roles:
    - role: rhel8-cis
      vars:
        rhel8cis_section1: "{{ enable_rhel8cis_section1 | default(false) | bool }}"
        rhel8cis_section2: "{{ enable_rhel8cis_section2 | default(false) | bool }}"
        rhel8cis_section3: "{{ enable_rhel8cis_section3 | default(false) | bool }}"
        rhel8cis_section4: "{{ enable_rhel8cis_section4 | default(false) | bool }}"
        rhel8cis_section5: "{{ enable_rhel8cis_section5 | default(false) | bool }}"
        rhel8cis_section6: "{{ enable_rhel8cis_section6 | default(false) | bool }}"
        rhel8cis_rule_1_1_1_1: false
        rhel8cis_rule_1_1_1_2: false
        rhel8cis_rule_1_1_1_3: false
        rhel8cis_rule_1_1_2_1: false
        rhel8cis_rule_1_1_2_2: false
        rhel8cis_rule_1_1_2_3: false
        rhel8cis_rule_1_1_2_4: false
        rhel8cis_rule_1_1_3_1: false
        rhel8cis_rule_1_1_3_2: false
        rhel8cis_rule_1_1_3_3: false
        rhel8cis_rule_1_1_3_4: false
        rhel8cis_rule_1_1_4_1: false
        rhel8cis_rule_1_1_4_2: false
        rhel8cis_rule_1_1_4_3: false
        rhel8cis_rule_1_1_4_4: false
        rhel8cis_rule_1_1_5_1: false
        rhel8cis_rule_1_1_5_2: false
        rhel8cis_rule_1_1_5_3: false
        rhel8cis_rule_1_1_5_4: false
        rhel8cis_rule_1_1_6_1: false
        rhel8cis_rule_1_1_6_2: false
        rhel8cis_rule_1_1_6_3: false
        rhel8cis_rule_1_1_6_4: false
        rhel8cis_rule_1_1_7_1: false
        rhel8cis_rule_1_1_7_2: false
        rhel8cis_rule_1_1_7_3: false
        rhel8cis_rule_1_1_7_4: false
        rhel8cis_rule_1_1_7_5: false
        rhel8cis_rule_1_1_8_1: false
        rhel8cis_rule_1_1_8_2: false
        rhel8cis_rule_1_1_8_3: false
        rhel8cis_rule_1_1_18: false
        rhel8cis_rule_1_1_19: false
        rhel8cis_rule_1_1_20: false
        rhel8cis_rule_1_1_21: false
        rhel8cis_rule_1_1_9: false
        rhel8cis_rule_1_1_10: false
        rhel8cis_rule_1_2_1: false
        rhel8cis_rule_1_2_2: false
        rhel8cis_rule_1_2_3: false
        rhel8cis_rule_1_2_4: false
        rhel8cis_rule_1_3_1: false
        rhel8cis_rule_1_3_2: false
        rhel8cis_rule_1_4_1: false
        rhel8cis_rule_1_4_2: false
        rhel8cis_rule_1_4_3: false
        rhel8cis_rule_1_5_1: false
        rhel8cis_rule_1_5_2: false
        rhel8cis_rule_1_5_3: false
        rhel8cis_rule_1_6_1: false
        rhel8cis_rule_1_6_2: false
        rhel8cis_rule_1_6_1_1: false
        rhel8cis_rule_1_6_1_2: false
        rhel8cis_rule_1_6_1_3: false
        rhel8cis_rule_1_6_1_4: false
        rhel8cis_rule_1_6_1_5: false
        rhel8cis_rule_1_6_1_6: false
        rhel8cis_rule_1_6_1_7: false
        rhel8cis_rule_1_6_1_8: false
        rhel8cis_rule_1_7_1: false
        rhel8cis_rule_1_7_2: false
        rhel8cis_rule_1_7_3: false
        rhel8cis_rule_1_7_4: false
        rhel8cis_rule_1_7_5: false
        rhel8cis_rule_1_7_6: false
        rhel8cis_rule_1_8_1: false
        rhel8cis_rule_1_8_2: false
        rhel8cis_rule_1_8_3: false
        rhel8cis_rule_1_8_4: false
        rhel8cis_rule_1_8_5: false
        rhel8cis_rule_1_9: false
        rhel8cis_rule_1_10: false
        rhel8cis_rule_1_11: false
        # Section 2 rules
        rhel8cis_rule_2_1_1: false
        rhel8cis_rule_2_1_2: false
        rhel8cis_rule_2_2_1: false
        rhel8cis_rule_2_2_2: false
        rhel8cis_rule_2_2_3: false
        rhel8cis_rule_2_2_4: false
        rhel8cis_rule_2_2_5: false
        rhel8cis_rule_2_2_6: false
        rhel8cis_rule_2_2_7: false
        rhel8cis_rule_2_2_8: false
        rhel8cis_rule_2_2_9: false
        rhel8cis_rule_2_2_10: false
        rhel8cis_rule_2_2_11: false
        rhel8cis_rule_2_2_12: false
        rhel8cis_rule_2_2_13: false
        rhel8cis_rule_2_2_14: false
        rhel8cis_rule_2_2_15: false
        rhel8cis_rule_2_2_16: false
        rhel8cis_rule_2_2_17: false
        rhel8cis_rule_2_2_18: false
        rhel8cis_rule_2_2_19: false
        rhel8cis_rule_2_2_20: false
        rhel8cis_rule_2_3_1: false
        rhel8cis_rule_2_3_2: false
        rhel8cis_rule_2_3_3: false
        rhel8cis_rule_2_3_4: false
        rhel8cis_rule_2_3_5: false
        rhel8cis_rule_2_3_6: false
        rhel8cis_rule_2_4: false
        # Section 3 rules
        rhel8cis_rule_3_1_1: false
        rhel8cis_rule_3_1_2: false
        rhel8cis_rule_3_1_3: false
        rhel8cis_rule_3_1_4: false
        rhel8cis_rule_3_2_1: false
        rhel8cis_rule_3_2_2: false
        rhel8cis_rule_3_3_1: false
        rhel8cis_rule_3_3_2: false
        rhel8cis_rule_3_3_3: false
        rhel8cis_rule_3_3_4: false
        rhel8cis_rule_3_3_5: false
        rhel8cis_rule_3_3_6: false
        rhel8cis_rule_3_3_7: false
        rhel8cis_rule_3_3_8: false
        rhel8cis_rule_3_3_9: false
        rhel8cis_rule_3_4_1_1: false
        rhel8cis_rule_3_4_1_2: false
        rhel8cis_rule_3_4_1_3: false
        rhel8cis_rule_3_4_1_4: false
        rhel8cis_rule_3_4_1_5: false
        rhel8cis_rule_3_4_1_6: false
        rhel8cis_rule_3_4_1_7: false
        rhel8cis_rule_3_4_2_1: false
        rhel8cis_rule_3_4_2_2: false
        rhel8cis_rule_3_4_2_3: false
        rhel8cis_rule_3_4_2_4: false
        rhel8cis_rule_3_4_2_5: false
        rhel8cis_rule_3_4_2_6: false
        rhel8cis_rule_3_4_2_7: false
        rhel8cis_rule_3_4_2_8: false
        rhel8cis_rule_3_4_2_9: false
        rhel8cis_rule_3_4_2_10: false
        rhel8cis_rule_3_4_2_11: false
        rhel8cis_rule_3_4_3_1_1: false
        rhel8cis_rule_3_4_3_1_2: false
        rhel8cis_rule_3_4_3_1_3: false
        rhel8cis_rule_3_4_3_2_1: false
        rhel8cis_rule_3_4_3_2_2: false
        rhel8cis_rule_3_4_3_2_3: false
        rhel8cis_rule_3_4_3_2_4: false
        rhel8cis_rule_3_4_3_2_5: false
        rhel8cis_rule_3_4_3_2_6: false
        rhel8cis_rule_3_4_3_3_1: false
        rhel8cis_rule_3_4_3_3_2: false
        rhel8cis_rule_3_4_3_3_3: false
        rhel8cis_rule_3_4_3_3_4: false
        rhel8cis_rule_3_4_3_3_5: false
        rhel8cis_rule_3_4_3_3_6: false

        # Section 4 rules
        rhel8cis_rule_4_1_1_1: false
        rhel8cis_rule_4_1_1_2: false
        rhel8cis_rule_4_1_1_3: false
        rhel8cis_rule_4_1_1_4: false
        rhel8cis_rule_4_1_2_1: false
        rhel8cis_rule_4_1_2_2: false
        rhel8cis_rule_4_1_2_3: false
        rhel8cis_rule_4_1_3_1: false
        rhel8cis_rule_4_1_3_2: false
        rhel8cis_rule_4_1_3_3: false
        rhel8cis_rule_4_1_3_4: false
        rhel8cis_rule_4_1_3_5: false
        rhel8cis_rule_4_1_3_6: false
        rhel8cis_rule_4_1_3_7: false
        rhel8cis_rule_4_1_3_8: false
        rhel8cis_rule_4_1_3_9: false
        rhel8cis_rule_4_1_3_10: false
        rhel8cis_rule_4_1_3_11: false
        rhel8cis_rule_4_1_3_12: false
        rhel8cis_rule_4_1_3_13: false
        rhel8cis_rule_4_1_3_14: false
        rhel8cis_rule_4_1_3_15: false
        rhel8cis_rule_4_1_3_16: false
        rhel8cis_rule_4_1_3_17: false
        rhel8cis_rule_4_1_3_18: false
        rhel8cis_rule_4_1_3_19: false
        rhel8cis_rule_4_1_3_20: false
        rhel8cis_rule_4_1_3_21: false
        rhel8cis_rule_4_2_1_1: false
        rhel8cis_rule_4_2_1_2: false
        rhel8cis_rule_4_2_1_3: false
        rhel8cis_rule_4_2_1_4: false
        rhel8cis_rule_4_2_1_5: false
        rhel8cis_rule_4_2_1_6: false
        rhel8cis_rule_4_2_1_7: false
        rhel8cis_rule_4_2_2_1_1: false
        rhel8cis_rule_4_2_2_1_2: false
        rhel8cis_rule_4_2_2_1_3: false
        rhel8cis_rule_4_2_2_1_4: false
        rhel8cis_rule_4_2_2_2: false
        rhel8cis_rule_4_2_2_3: false
        rhel8cis_rule_4_2_2_4: false
        rhel8cis_rule_4_2_2_5: false
        rhel8cis_rule_4_2_2_6: false
        rhel8cis_rule_4_2_2_7: false
        rhel8cis_rule_4_2_3: false
        rhel8cis_rule_4_3: false

        # Section 5 rules
        rhel8cis_rule_5_1_1: false
        rhel8cis_rule_5_1_2: false
        rhel8cis_rule_5_1_3: false
        rhel8cis_rule_5_1_4: false
        rhel8cis_rule_5_1_5: false
        rhel8cis_rule_5_1_6: false
        rhel8cis_rule_5_1_7: false
        rhel8cis_rule_5_1_8: false
        rhel8cis_rule_5_1_9: false
        rhel8cis_rule_5_2_1: false
        rhel8cis_rule_5_2_2: false
        rhel8cis_rule_5_2_3: false
        rhel8cis_rule_5_2_4: false
        rhel8cis_rule_5_2_5: false
        rhel8cis_rule_5_2_6: false
        rhel8cis_rule_5_2_7: false
        rhel8cis_rule_5_2_8: false
        rhel8cis_rule_5_2_9: false
        rhel8cis_rule_5_2_10: false
        rhel8cis_rule_5_2_12: false
        rhel8cis_rule_5_2_11: false
        rhel8cis_rule_5_2_13: false
        rhel8cis_rule_5_2_14: false
        rhel8cis_rule_5_2_15: false
        rhel8cis_rule_5_2_16: false
        rhel8cis_rule_5_2_17: false
        rhel8cis_rule_5_2_18: false
        rhel8cis_rule_5_2_19: false
        rhel8cis_rule_5_2_20: false
        rhel8cis_rule_5_3_1: false
        rhel8cis_rule_5_3_2: false
        rhel8cis_rule_5_3_3: false
        rhel8cis_rule_5_3_4: false
        rhel8cis_rule_5_3_5: false
        rhel8cis_rule_5_3_6: false
        rhel8cis_rule_5_3_7: false
        rhel8cis_rule_5_4_1: false
        rhel8cis_rule_5_4_2: false
        rhel8cis_rule_5_5_1: false
        rhel8cis_rule_5_5_2: false
        rhel8cis_rule_5_5_3: false
        rhel8cis_rule_5_5_4: false
        rhel8cis_rule_5_5_5: false
        rhel8cis_rule_5_6_1_1: false
        rhel8cis_rule_5_6_1_2: false
        rhel8cis_rule_5_6_1_3: false
        rhel8cis_rule_5_6_1_4: false
        rhel8cis_rule_5_6_1_5: false
        rhel8cis_rule_5_6_2: false
        rhel8cis_rule_5_6_3: false
        rhel8cis_rule_5_6_4: false
        rhel8cis_rule_5_6_5: false

        # Section 6 rules
        rhel8cis_rule_6_1_1: false
        rhel8cis_rule_6_1_2: false
        rhel8cis_rule_6_1_3: false
        rhel8cis_rule_6_1_4: false
        rhel8cis_rule_6_1_5: false
        rhel8cis_rule_6_1_6: false
        rhel8cis_rule_6_1_7: false
        rhel8cis_rule_6_1_8: false
        rhel8cis_rule_6_1_9: false
        rhel8cis_rule_6_1_10: false
        rhel8cis_rule_6_1_11: false
        rhel8cis_rule_6_1_12: false
        rhel8cis_rule_6_1_13: false
        rhel8cis_rule_6_1_14: false
        rhel8cis_rule_6_1_15: false
        rhel8cis_rule_6_2_1: false
        rhel8cis_rule_6_2_2: false
        rhel8cis_rule_6_2_3: false
        rhel8cis_rule_6_2_4: false
        rhel8cis_rule_6_2_5: false
        rhel8cis_rule_6_2_6: false
        rhel8cis_rule_6_2_7: false
        rhel8cis_rule_6_2_8: false
        rhel8cis_rule_6_2_9: false
        rhel8cis_rule_6_2_10: false
        rhel8cis_rule_6_2_11: false
        rhel8cis_rule_6_2_12: false
        rhel8cis_rule_6_2_13: false
        rhel8cis_rule_6_2_14: false
        rhel8cis_rule_6_2_15: false
        rhel8cis_rule_6_2_16: false





